name: fl_observable_example
description: Example application.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/rosewareGit/fl_observable
issue_tracker: https://github.com/rosewareGit/fl_observable/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_observable: ^1.0.2
  fl_observable:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Regular.ttf
        - asset: assets/fonts/Montserrat/Bold.ttf
          weight: 700
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans/Regular.ttf
        - asset: assets/fonts/JosefinSans/Bold.ttf
          weight: 700
