name: fl_observable
description: Flutter components for dart_observable package
version: 1.0.0
repository: https://github.com/rosewareGit/fl_observable
issue_tracker: https://github.com/rosewareGit/fl_observable/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_observable: ^1.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
